sudo: false
language: c
compiler: clang

addons:
  apt:
    packages:
      - gcc-multilib

env:
  global:
    - ARCH=x64
  matrix:
    - CONFIG=asan
    - CONFIG=msan
    - CONFIG=ubsan
    - CONFIG=debug
    - CONFIG=release
    - CONFIG=release ARCH=x32

os:
  - linux

matrix:
  include:
    - os: osx
      env: CONFIG=release
      compiler: clang
  allow_failures:
    - os: osx

script:
  make config=${CONFIG} arch=${ARCH} test

cache:
  directories:
    - .deps/usr

after_failure:
  cat asan.* ubsan.* msan.* || true
