sudo: false
language: c
compiler: clang

env:
  matrix:
    - CONFIG=asan
    - CONFIG=msan
    - CONFIG=ubsan
    - CONFIG=debug
    - CONFIG=release

os:
  - linux

matrix:
  include:
    - os: linux
      env: CONFIG=release CFLAGS=-m32 LDFLAGS=-m32
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: linux
      compiler: gcc
      env:
        - CONFIG=coverage 
        - RUNNER=.deps/usr/bin/qemu-armeb
      addons:
        apt:
          packages:
            - qemu-user-static
      install:
        - pip install --user cpp-coveralls
        - . .ci/arm_test_setup.sh
      after_success:
        - coveralls -b build --gcov $(pwd)/.deps/usr/bin/armeb-linux-gnueabihf-gcov --gcov-options '\-lp'
    - os: linux
      compiler: gcc
      env:
        - CONFIG=release
        - CFLAGS=-DNO_NATIVE_IEEE754 
    - os: linux
      compiler: gcc
      env:
        - CONFIG=release
        - CFLAGS=-DNO_NATIVE_IEEE754 
        - RUNNER=.deps/usr/bin/qemu-armeb
      addons:
        apt:
          packages:
            - qemu-user-static
      install:
        - . .ci/arm_test_setup.sh
    - os: osx
      env: CONFIG=release
      compiler: clang
  allow_failures:
    - os: osx

script:
  make config=${CONFIG} test

cache:
  directories:
    - .deps/usr

after_failure:
  cat asan.* ubsan.* msan.* || true
