sudo: false
language: c
compiler: clang

env:
  global:
    - VERBOSE=1
  matrix:
    - CONFIG=asan
    - CONFIG=msan
    - CONFIG=ubsan
    - CONFIG=debug
    - CONFIG=release
    - CONFIG=amalgamation
    - CONFIG=release ANSI=1

os:
  - linux

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CONFIG=release CFLAGS=-m32 LDFLAGS=-m32
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: linux
      compiler: gcc
      env:
        - CONFIG=armeb CFLAGS='-DNDEBUG -g --coverage' LDFLAGS=--coverage
      before_install:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls -b . --gcov $(pwd)/.deps/usr/bin/armeb-linux-gnueabihf-gcov --gcov-options '\-lp'
    - os: osx
      env: CONFIG=release
      compiler: gcc

script:
  make config=${CONFIG} test

cache:
  directories:
    - .deps/usr

after_failure:
  cat asan.* ubsan.* msan.* || true
