sudo: false
language: c
compiler: clang

env:
  matrix:
    - CONFIG=asan
    - CONFIG=msan
    - CONFIG=ubsan
    - CONFIG=debug
    - CONFIG=release

os:
  - linux

matrix:
  include:
    - os: linux
      env: CONFIG=release CFLAGS=-m32 LDFLAGS=-m32
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: linux
      env: CONFIG=coverage
      compiler: gcc
      before_install:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls -b build --gcov-options '\-lp'
    - os: osx
      env: CONFIG=release
      compiler: clang
  allow_failures:
    - os: osx

script:
  make config=${CONFIG} test

cache:
  directories:
    - .deps/usr

after_failure:
  cat asan.* ubsan.* msan.* || true
